name: Build Latest

on: [push]

env:
  DOTNET_SDK_VERSION: '6.0.x'

jobs:
  build-win-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true
      
      - name: Build win-x64
        run: cd ./PictureEncoder-Console/ | dotnet publish -r win-x64 -c Release -o ../artifact-x64 /p:PublishSingleFile=true --no-self-contained
        
      - name: Build win-arm64
        run: cd ./PictureEncoder-WPF/ | dotnet publish -r win-x64 -c Release -o ../artifact-arm64 /p:PublishSingleFile=true --no-self-contained

      - name: Upload Console Artifact[win-x64]
        uses: actions/upload-artifact@v3
        with:
          name: PictureEncoder_Console_win-x64
          path: artifact-x64/PictureEncoder-Console.exe
          
      - name: Upload Console Artifact[win-arm64]
        uses: actions/upload-artifact@v3
        with:
          name: PictureEncoder_Console_win-arm64
          path: artifact-arm64/PictureEncoder-Console.exe
          
      - name: Upload WPF Artifact[win-x64]
        uses: actions/upload-artifact@v3
        with:
          name: PictureEncoder_WPF_win-x64
          path: artifact-x64/PictureEncoder-WPF.exe
